// lib/products.ts
export function getProductData(id: string) {
  const products = {
    "1": {
      id: "1",
      name: "ASUS ROG Strix RTX 4090",
      image:
        "https://dlcdnwebimgs.asus.com/files/media/015AF38A-127E-4FA8-9700-6D92BB2760C1/v2/img/kv/pd.png",
      images: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTd1r8PjrBdYQ_SqTFbXIf22QqINNN3S1Dw9A&s",
        "https://images-cdn.ubuy.co.in/65466f2a6337012fd975e940-asus-rog-strix-geforce-rtx-4090-oc.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp5wcx4qAyuFb1pb2bPWtxtcBFDu7sPPZhyg&s",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaNm8PGkF4IM1KbjfjcuXC8Nc3Hs6MZuQ7UA&s",
      ],
      price: "$1,599.99",
      originalPrice: "$1,799.99",
      rating: 4.9,
      reviews: 234,
      brand: "ASUS",
      series: "VivoBook 14 (X1405VA)",
      cpu: "Intel® Core™ i5-13420H Processor 2.1 GHz",
      graphics: "Intel Iris Xe Graphics",
      display: "14.0-inch WUXGA IPS Panel",
      os: "Windows 11 Home",
      memory: "8GB DDR4",
      storage: "512GB NVMe SSD",
      connectivity: "Wi-Fi 6E + Bluetooth 5.3",
      camera: "720p HD",
      audio: "SonicMaster Speakers",
      battery: "42WHrs, 3-cell Li-ion",
      weight: "1.60 kg",
      warranty: "2 Year Int'l Warranty",
      description:
        "The ASUS VivoBook 14 X1405VA is designed for productivity and entertainment.",
      features: [
        "13th Gen Intel Core i5 Processor",
        "14-inch WUXGA Display",
        "8GB DDR4 RAM",
        "512GB PCIe 4.0 SSD",
        "Wi-Fi 6E Connectivity",
        "Lightweight Design",
        "Comprehensive I/O Ports",
        "ASUS SonicMaster Audio",
      ],
    },
    "3": {
      id: "3",
      name: "MSI Gaming Laptop GF63 Thin 11UC-692",
      image:
        "https://dlcdnwebimgs.asus.com/files/media/015AF38A-127E-4FA8-9700-6D92BB2760C1/v2/img/kv/pd.png",
      images: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTd1r8PjrBdYQ_SqTFbXIf22QqINNN3S1Dw9A&s",
        "https://images-cdn.ubuy.co.in/65466f2a6337012fd975e940-asus-rog-strix-geforce-rtx-4090-oc.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp5wcx4qAyuFb1pb2bPWtxtcBFDu7sPPZhyg&s",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaNm8PGkF4IM1KbjfjcuXC8Nc3Hs6MZuQ7UA&s",
      ],
      price: "₹75,000",
      originalPrice: "₹82,000",
      reviews: 89,
      brand: "MSI",
      series: "GF63 Thin 11UC",
      cpu: "Intel® Core™ i5-11400H",
      graphics: "NVIDIA GeForce RTX 3050",
      display: "15.6-inch FHD 144Hz",
      os: "Windows 11 Home",
      memory: "8GB DDR4",
      storage: "512GB NVMe SSD",
      connectivity: "Wi-Fi 6 + Bluetooth 5.2",
      camera: "HD 720p",
      audio: "Nahimic 3 Speakers",
      battery: "51WHr",
      weight: "1.86 kg",
      warranty: "2 Year Warranty",
      description:
        "The MSI GF63 Thin is a powerful gaming laptop for gamers and creators.",
      features: [
        "Intel Core i5 Processor",
        "NVIDIA RTX 3050 GPU",
        "144Hz Display",
        "MSI Center Software",
        "Cooler Boost 5 Thermal",
        "Red Backlit Keyboard",
        "Comprehensive Connectivity",
        "Nahimic 3 Audio",
      ],
    },
  };

  return products[id as keyof typeof products] || products["1"];
}
